---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
      - 192.168.255.6/30
      routes:
      - to: 0.0.0.0/0
        via: 192.168.255.5
      - to: 192.168.58.0/24
        via: 192.168.255.5
      - to: 192.168.57.0/24
        via: 192.168.255.5
    eth2:
      addresses:
      - 192.168.59.1/25
    eth5:
      addresses:
      - 192.168.56.30/24
