---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
      - 192.168.255.10/30
      routes:
      - to: 0.0.0.0/0
        via: 192.168.255.9
      - to: 192.168.59.0/24
        via: 192.168.255.9
      - to: 192.168.57.0/24
        via: 192.168.255.9
    eth4:
      addresses:
      - 192.168.58.129/26

    eth6:
      addresses:
      - 192.168.56.20/24
