---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
      - 192.168.57.2/28
      routes:
      - to: 0.0.0.0/0
        via: 192.168.57.1
    eth2:
      addresses:
      - 192.168.56.12/24
