---
- hosts: all # part running on all hosts
  become: true
  tasks:

#  - name: Update repositories cache
#    apt:
#      update_cache: yes
#
  - name: install packages iptables
    apt:
      name: iptables
      state: latest
      update_cache: yes
    when: (ansible_hostname == "inetRouter")

  - name: install packages netplan 
    apt:
      name: netplan.io
      state: latest
      update_cache: yes 

  - name: Set up NAT on inetRouter
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    with_items:
      - { src: "iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
      - { src: "iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
    when: (ansible_hostname == "inetRouter")

  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
    when: "'routers' in group_names"

  - name: disable default route
    template: 
      src: 00-installer-config.yaml
      dest: /etc/netplan/00-installer-config.yaml
      owner: root
      group: root
      mode: 0600
    when: (ansible_hostname != "inetRouter") 

  - name: add default gateway for centralRouter
    template: 
      src: 50-vagrant_{{ansible_hostname}}.yml
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0600

  - name: restart all hosts
    reboot:
      reboot_timeout: 600

- hosts: servers # part running on all hosts
  become: true
  tasks:

#  - name: Update repositories cache
#    apt:
#      update_cache: yes
#
  - name: install packages traceroute
    apt:
      name: traceroute
      state: latest
      update_cache: yes
 
